version: "3"

services:
  app:
    build:
      context: ./
    volumes:
      - ./data:/data
    restart: unless-stopped
    devices:
      - "/dev/dvb"
    stdin_open: true # docker run -i
    tty: true # docker run -t
